- hosts: all
  tasks:
  - name: install pacakges
    yum:
      name: 
        - httpd
        - wget
        - tree
        - vim
      state: latest
  - name: Start service httpd, if not started
    service:
      name: httpd
      state: started
      enabled: yes
  - name: stop httpd
    service:
      name: httpd
      state: stopped    
  # - name: remove the Apache package
  #   yum:
  #     name: httpd
  #     state: absent       
    