- name: Download wordpress
  get_url:
    url: "{{ url_package }}"
    dest: "{{ destination }}"

- name: Extract wordpress
  unarchive:
    src: "{{ source_pack }}"
    dest: /tmp 
    remote_src: yes

- name: Copy file with owner and permissions
  copy:
    src: /tmp/wordpress/.
    dest: /var/www/html
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: '755'    
    remote_src: yes

- name: Template a file to /var/www/html
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wp-config.php   

- name: Start and enable Apache
  service:
    name: "{{ package }}"
    state: restarted

